apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployed
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: deployed
rules:
  -
    apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - events
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deployed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployed
subjects:
- kind: ServiceAccount
  name: deployed
  namespace: deployed